window.jQuery = require('jquery');
window.Tether = require('tether');
require('bootstrap');
require('jquery.appear');
//require('lightbox');
require('smoothscroll');
require('@fancyapps/fancybox');
require('isotope-layout');
require('angular');
require('angular-route');
require('angular-sanitize');
require('ui-cropper');
require('@meanie/angular-geo-locate');
require('bootstrap-3-typeahead');
require('angular-google-maps-native');
require('angular-sweetalert-2/dist/angular-sweetalert2.min');
require('angular1-star-rating');
require('angular-recaptcha');
require('angularjs-social-login');
window.swal = require('sweetalert2');
window.fuzzy = require('fuzzymatchingjs').fuzzyMatching;
window.JSON8 = require('json8');
window.JSON8Patch = require('json8-patch');
window.moment = require('moment');
window.bowser = require('bowser');
require('./src/polyfill');
